"""initial schema

Revision ID: 77d7de01138c
Revises: 
Create Date: 2026-07-17 19:20:31.483721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d7de01138c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_expenses_user_id'), ['user_id'], unique=False)

    op.create_table('purchase_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_number', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('estimated_retail_total', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('pallet_count', sa.Integer(), nullable=True),
    sa.Column('bid_price', sa.Float(), nullable=False),
    sa.Column('auction_fee_percent', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('is_purchased', sa.Boolean(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_platform', sa.String(length=120), nullable=True),
    sa.Column('source_country', sa.String(length=10), nullable=True),
    sa.Column('category', sa.String(length=120), nullable=True),
    sa.Column('lot_condition', sa.String(length=80), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_lots_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_lots_is_purchased'), ['is_purchased'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_lots_lot_number'), ['lot_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_purchase_lots_source_country'), ['source_country'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_lots_source_platform'), ['source_platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_lots_user_id'), ['user_id'], unique=False)

    op.create_table('purchase_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=120), nullable=False),
    sa.Column('tag_type', sa.String(length=20), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tag_type', 'label', name='uq_tag_user_type_label')
    )
    with op.batch_alter_table('purchase_tags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_tags_tag_type'), ['tag_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_tags_user_id'), ['user_id'], unique=False)

    op.create_table('lot_inspections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('inspection_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('qty_total_received', sa.Integer(), nullable=False),
    sa.Column('qty_new', sa.Integer(), nullable=False),
    sa.Column('qty_good', sa.Integer(), nullable=False),
    sa.Column('qty_damaged', sa.Integer(), nullable=False),
    sa.Column('qty_parts', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['purchase_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lot_inspections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lot_inspections_lot_id'), ['lot_id'], unique=True)

    op.create_table('raw_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('supplier', sa.String(length=150), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=False),
    sa.Column('estimated_resale_value', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.DateTime(timezone=True), nullable=False),
    sa.Column('purchase_lot_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['purchase_lot_id'], ['purchase_lots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('raw_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_products_purchase_lot_id'), ['purchase_lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_products_user_id'), ['user_id'], unique=False)

    op.create_table('rex_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('date_created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lot_id'], ['purchase_lots.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rex_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rex_insights_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rex_insights_user_id'), ['user_id'], unique=False)

    op.create_table('stock_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('sell_price', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('condition', sa.String(length=50), nullable=True),
    sa.Column('packaging_condition', sa.String(length=50), nullable=True),
    sa.Column('target_platform', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('marketplace_title', sa.String(length=255), nullable=True),
    sa.Column('marketplace_description', sa.Text(), nullable=True),
    sa.Column('main_image_path', sa.String(length=255), nullable=True),
    sa.Column('date_entry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_product_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_product_id'], ['raw_products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stock_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stock_items_raw_product_id'), ['raw_product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_items_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_stock_items_user_id'), ['user_id'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('platform', sa.String(length=80), nullable=True),
    sa.Column('sale_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fees', sa.Float(), nullable=False),
    sa.Column('shipping_cost', sa.Float(), nullable=False),
    sa.Column('buyer_info', sa.Text(), nullable=True),
    sa.Column('stock_item_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_stock_item_id'), ['stock_item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_sales_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_user_id'))
        batch_op.drop_index(batch_op.f('ix_sales_stock_item_id'))

    op.drop_table('sales')
    with op.batch_alter_table('stock_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stock_items_user_id'))
        batch_op.drop_index(batch_op.f('ix_stock_items_status'))
        batch_op.drop_index(batch_op.f('ix_stock_items_raw_product_id'))

    op.drop_table('stock_items')
    with op.batch_alter_table('rex_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rex_insights_user_id'))
        batch_op.drop_index(batch_op.f('ix_rex_insights_lot_id'))

    op.drop_table('rex_insights')
    with op.batch_alter_table('raw_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_products_user_id'))
        batch_op.drop_index(batch_op.f('ix_raw_products_purchase_lot_id'))

    op.drop_table('raw_products')
    with op.batch_alter_table('lot_inspections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lot_inspections_lot_id'))

    op.drop_table('lot_inspections')
    with op.batch_alter_table('purchase_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_tags_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_tags_tag_type'))

    op.drop_table('purchase_tags')
    with op.batch_alter_table('purchase_lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_lots_user_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_lots_source_platform'))
        batch_op.drop_index(batch_op.f('ix_purchase_lots_source_country'))
        batch_op.drop_index(batch_op.f('ix_purchase_lots_lot_number'))
        batch_op.drop_index(batch_op.f('ix_purchase_lots_is_purchased'))
        batch_op.drop_index(batch_op.f('ix_purchase_lots_category'))

    op.drop_table('purchase_lots')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_user_id'))
        batch_op.drop_index(batch_op.f('ix_expenses_category'))

    op.drop_table('expenses')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
